# Generated by Django 4.2.6 on 2023-11-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
